name: Generate Contribution Snake

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:   # Allows you to run it manually
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1 — Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2 — Generate snake animation (SVG)
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: hardiksolanki
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 3 — Push the generated files to the output branch
      - name: Push Generated Snake Files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
